# Generated by Django 2.1.5 on 2019-02-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addbug', models.IntegerField(verbose_name='新增')),
                ('repair', models.IntegerField(verbose_name='修复')),
                ('activation', models.IntegerField(verbose_name='激活')),
                ('ignore', models.IntegerField(verbose_name='忽略')),
                ('surplus', models.IntegerField(verbose_name='剩余')),
                ('deadly', models.IntegerField(verbose_name='致命')),
                ('serious', models.IntegerField(verbose_name='严重')),
                ('ordinary', models.IntegerField(verbose_name='普通')),
                ('light', models.IntegerField(verbose_name='轻度')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(choices=[('LK', 'Lu Kai'), ('LMD', 'Liu Meng Die'), ('LXH', 'Li Xiao Hui'), ('OY', 'Ou Yang Gao Fen'), ('XJM', 'Xing Jing Ming')], default='LK', max_length=100)),
                ('demandname', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'student',
                'ordering': ['pub_date'],
            },
        ),
        migrations.AddField(
            model_name='state',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Student'),
        ),
    ]
